name: Monitoring Demo

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Run Step
      run: echo "Pipeline running"

    - name: Fail Step
      run: exit 0

  security:
    runs-on: ubuntu-latest
    needs: build   # run after build job

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # 🔍 Scan for hardcoded secrets
    - name: TruffleHog Secret Scan
      id: scan
      uses: trufflesecurity/trufflehog@main
      with:
        path: ./
        base: HEAD~1
        head: HEAD

    # ❌ Fail pipeline if secrets detected
    - name: Fail if hardcoded password found
      if: failure()
      run: |
        echo "❌ Hardcoded password detected! Pipeline failed."
        exit 1
